---
 - name: Install packages and update cache 
   apt: 
     name: [ethtool, iptables, hping3, iperf3]
     update_cache: yes

 - name: Execute command to create queues
   ansible.builtin.shell: ethtool -L enp0s3 combined 4

 - name: Create queues discipline with tc-cbs credit base
   ansible.builtin.shell: tc qdisc add dev enp0s3 parent root handle 6666 mqprio num_tc 3 map 2 2 1 0 2 2 2 2 2 2 2 2 2 2 2 2 queues 1@0 1@1 2@2 hw 0
   ignore_errors: true

 - name: Create first queue policy
   ansible.builtin.shell: tc qdisc replace dev enp0s3 parent 6666:1 cbs idleslope 98688 sendslope -901312 hicredit 153 locredit -1389 offload 0
   # ignore_errors: true

 - name: Create second queue policy
   ansible.builtin.shell: tc qdisc replace dev enp0s3 parent 6666:2 cbs idleslope 3648 sendslope -996352 hicredit 12 locredit -113 offload 0
   # ignore_errors: true

# - name: Modify mangle table to mark packet for queue discipline on port 7777
#   ansible.builtin.iptables:
#     table: mangle
#     chain: POSTROUTING
#     protocol: udp
#     destination_port: 7777
#     set_dscp_mark: 6666:2
#
# - name: Modify mangle table to mark packet for queue discipline on port 7777
#   ansible.builtin.iptables:
#     table: mangle
#     chain: POSTROUTING
#     protocol: udp
#     source_port: 7777
#     set_dscp_mark: 6666:2
# - name: Use iptables to tag packet per queue on source port 7777
#   ansible.builtin.shell: iptables -t mangle -A POSTROUTING -p udp --sport 7777 -j CLASSIFY --set-class 6666:2
#
# - name: Use iptables to tag packet per queue on dest port 7777
#   ansible.builtin.shell: iptables -t mangle -A POSTROUTING -p udp --dport 7777 -j CLASSIFY --set-class 6666:2
#
# - name: Use iptables to tag packet per queue on source port 6666
#   ansible.builtin.shell: iptables -t mangle -A POSTROUTING -p udp --sport 6666 -j CLASSIFY --set-class 6666:3
#
# - name: Use iptables to tag packet per queue on dest port 6666
#  ansible.builtin.shell: iptables -t mangle -A POSTROUTING -p udp --dport 6666 -j CLASSIFY --set-class 6666:3
 - name: Create iptables folder if not exist
   ansible.builtin.file:
     path: /etc/iptables
     owner: root
     group: root
     state: directory
     mode: '0644'

 - name: Copy Iptables rules
   ansible.builtin.copy:
     src: rules.v4
     dest: /etc/iptables/rules.v4
     owner: root
     group: root
     mode: '0644'
   notify: load iptables
